services:
  dyfi-updater:
    build: .
    container_name: dyfi-updater
    environment:
      - DYFI_USER=${DYFI_USER}
      - DYFI_PASS=${DYFI_PASS}
      - DYFI_HOSTS=${DYFI_HOSTS}
    restart: unless-stopped

volumes:
  dyfi-data:
